import React, { useState, useEffect } from 'react';
import { generateCapabilityDescription } from '../services/geminiService';
import type { Capability } from '../types';

// Icons
const SparklesIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-brand-accent">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.898 20.562L16.5 21.75l-.398-1.188a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.188-.398a2.25 2.25 0 001.423-1.423L16.5 15.75l.398 1.188a2.25 2.25 0 001.423 1.423L19.5 18.75l-1.188.398a2.25 2.25 0 00-1.423 1.423z" />
    </svg>
);

const LockClosedIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-brand-accent">
        <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
    </svg>
);

const ArrowsRightLeftIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-brand-accent">
        <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h18m-7.5-12L21 9m0 0L16.5 4.5M21 9H3" />
    </svg>
);


const initialCapabilities: Omit<Capability, 'description'>[] = [
  { id: 'launchpad', title: 'Ordinals & Runes Launchpad', icon: <SparklesIcon /> },
  { id: 'vault', title: 'vetKeys Encrypted Vault', icon: <LockClosedIcon /> },
  { id: 'swaps', title: 'Trustless Cross-Chain Swaps', icon: <ArrowsRightLeftIcon /> },
];

const LoadingSkeleton: React.FC = () => (
    <div className="bg-brand-blue p-6 rounded-lg animate-pulse">
        <div className="h-8 w-8 bg-brand-light-blue rounded mb-4"></div>
        <div className="h-6 bg-brand-light-blue rounded w-3/4 mb-4"></div>
        <div className="h-4 bg-brand-light-blue rounded w-full mb-2"></div>
        <div className="h-4 bg-brand-light-blue rounded w-5/6"></div>
    </div>
);

const AdvancedCapabilities: React.FC = () => {
  const [capabilities, setCapabilities] = useState<Capability[]>(initialCapabilities.map(c => ({...c, description: ''})));
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDescriptions = async () => {
      setLoading(true);
      const updatedCapabilities = await Promise.all(
        initialCapabilities.map(async (capability) => {
          const description = await generateCapabilityDescription(capability.title);
          return { ...capability, description };
        })
      );
      setCapabilities(updatedCapabilities);
      setLoading(false);
    };

    fetchDescriptions();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <section className="py-16 md:py-24 animate-slide-up">
      <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">
        Explore Advanced <span className="text-transparent bg-clip-text bg-gradient-to-r from-btc-orange to-yellow-400">BTCFi Capabilities</span>
      </h2>
      <p className="max-w-3xl mx-auto text-center text-lg text-gray-400 mb-12 -mt-8">
        Discover project ideas from the hackathon, powered by ICP's unique features.
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {loading ? (
          <>
            <LoadingSkeleton />
            <LoadingSkeleton />
            <LoadingSkeleton />
          </>
        ) : (
          capabilities.map((capability) => (
            <div key={capability.id} className="bg-brand-blue p-6 rounded-lg border border-brand-light-blue shadow-lg transform transition-transform duration-300 hover:-translate-y-1 hover:border-brand-accent">
              <div className="mb-4">{capability.icon}</div>
              <h3 className="text-xl font-bold text-white mb-3">{capability.title}</h3>
              <p className="text-gray-300">{capability.description}</p>
            </div>
          ))
        )}
      </div>
       <p className="text-center text-sm text-gray-500 mt-4">Capability descriptions generated by Gemini API.</p>
    </section>
  );
};

export default AdvancedCapabilities;
