
import React, { useState, useEffect } from 'react';
import { generateUseCaseDescription } from '../services/geminiService';
import type { UseCase } from '../types';

const initialUseCases: UseCase[] = [
  { id: 'dex', title: 'Decentralized Exchanges (DEXs)', description: '' },
  { id: 'lending', title: 'Lending & Borrowing', description: '' },
  { id: 'yield', title: 'Yield Farming & Staking', description: '' },
];

const LoadingSkeleton: React.FC = () => (
    <div className="bg-brand-blue p-6 rounded-lg animate-pulse">
        <div className="h-6 bg-brand-light-blue rounded w-3/4 mb-4"></div>
        <div className="h-4 bg-brand-light-blue rounded w-full mb-2"></div>
        <div className="h-4 bg-brand-light-blue rounded w-5/6"></div>
    </div>
);

const UseCases: React.FC = () => {
  const [useCases, setUseCases] = useState<UseCase[]>(initialUseCases);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDescriptions = async () => {
      setLoading(true);
      const updatedUseCases = await Promise.all(
        initialUseCases.map(async (useCase) => {
          const description = await generateUseCaseDescription(useCase.title);
          return { ...useCase, description };
        })
      );
      setUseCases(updatedUseCases);
      setLoading(false);
    };

    fetchDescriptions();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <section className="py-16 md:py-24 animate-slide-up">
      <h2 className="text-3xl md:text-4xl font-bold text-center mb-12">
        Revolutionary <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-accent to-teal-300">DeFi Use Cases</span>
      </h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {loading ? (
          <>
            <LoadingSkeleton />
            <LoadingSkeleton />
            <LoadingSkeleton />
          </>
        ) : (
          useCases.map((useCase) => (
            <div key={useCase.id} className="bg-brand-blue p-6 rounded-lg border border-brand-light-blue shadow-lg transform transition-transform duration-300 hover:-translate-y-1">
              <h3 className="text-xl font-bold text-white mb-3">{useCase.title}</h3>
              <p className="text-gray-300">{useCase.description}</p>
            </div>
          ))
        )}
      </div>
       <p className="text-center text-sm text-gray-500 mt-4">Use case descriptions generated by Gemini API.</p>
    </section>
  );
};

export default UseCases;
